# Site
name: "IEEE-VIT"
description: "Official Blog of IEEE-VIT"
meta_description: "IEEE Vidyalankar, ieee.vit.edu.in, https://ieee.vit.edu.in"
logo: 'assets/images/ieeevit-blue-1-5017x1103.png'
favicon: 'assets/images/logo.png'
baseurl: /ieeevitblog
google_analytics: 'UA-46278016-1'


# Authors
authors:
  Shikha Jha:
    name: Shikha Jha
    display_name: Shikha Jha
    gravatar: ed67abe03c65a6f4b99e0099b881df8d
    email: 
    web: 
    description: "General Secretary 2018. Co-ordinator of IRIS 2018."
  Saurabh Fegade:
    name: Saurabh Fegade
    display_name: Saurabh Fegade
    gravatar: 66849570f3b4033d8c35600632f4237a
    email: 
    web: 
    description: "Webmaster 2018. Voyager Coordinator 2018 and Web Team Member"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

theme: jekyll-theme-minimal
